export const THEMES = {
  blue: {
    "--primary-color": "#3b82f6",
    "--primary-light-color": "#eff6ff",
    "--primary-contrast-color": "#ffffff",
    "--secondary-color": "#9c27b0",
    "--secondary-contrast-color": "#ffffff",
    "--success-color": "#4caf50",
    "--success-contrast-color": "#ffffff",
    "--warning-color": "#ff9800",
    "--warning-contrast-color": "#000000",
    "--info-color": "#03a9f4",
    "--info-contrast-color": "#ffffff",
  },
  red: {
    "--primary-color": "#d32f2f",
    "—-primary-light-color": "#fef2f2",
    "--primary-contrast-color": "#ffffff",
    "--secondary-color": "#ff4081",
    "--secondary-contrast-color": "#ffffff",
    "--success-color": "#4caf50",
    "--success-contrast-color": "#ffffff",
    "--warning-color": "#ff9800",
    "--warning-contrast-color": "#000000",
    "_-info-color": "#03a9f4",
    "--info-contrast-color": "#ffffff",
  },
  green: {
    "—-primary-color": "#388e3c",
    "--primary-light-color": "#f0fdf4",
    "--primary-contrast-color": "#ffffff",
    "--secondary-color": "#8e24aa",
    "--secondary-contrast-color": "#ffffff",
    "--success-color": "#4caf50",
    "--success-contrast-color": "#ffffff",
    "--warning-color": "#ffeb3b",
    "--warning-contrast-color": "#000000",
    "--info-color": "#03a9f4",
    "--info-contrast-color": "#ffffff",
  },
  orange: {
    "--primary-color": "#f57c00",
    "--primary-light-color": "#fff7ed",
    "--primary-contrast-color": "#ffffff",
    "--secondary-color": "#7b1fa2",
    "--secondary-contrast-color": "#ffffff",
    "--success-color": "#388e3c",
    "--success-contrast-color": "#ffffff",
    "--warning-color": "#ff9800",
    "--warning-contrast-color": "#000000",
    "--info-color": "#0288d1",
    "--info-contrast-color": "#ffffff",
  },
  purple: {
    "—-primary-color": "#7b1fa2",
    "--primary-light-color": "#f3e8ff",
    "--primary-contrast-color": "#ffffff",
    "--secondary-color": "#ff4081",
    "--secondary-contrast-color": "#ffffff",
    "--success-color": "#388e3c",
    "--success-contrast-color": "#ffffff",
    "--warning-color": "#fbc02d",
    "--warning-contrast-color": "#000000",
    "--info-color": "#03a9f4",
    "--info-contrast-color": "#ffffff",
  },
};
